application: deadbolt-password-generato-hrd
version: db-bootstrap-hyzenthlay
api_version: 1
runtime: python27
threadsafe: yes

default_expiration: "7d"

handlers:
- url: /(.*\.(gif|png|jpg|css|js|ico|xml))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|css|js|ico|xml))

- url: /googleda51c33bed70f3e1.html
  static_files: static/googleda51c33bed70f3e1.html
  upload: static/googleda51c33bed70f3e1.html

- url: /(.*)
  script: controllers.deadbolt.app

libraries:
- name: webapp2
  version: "2.5.2"